- name: htttp setup
  hosts: 192.168.85.128
  tasks:
    - name: install htttpd
      yum:
        name: httpd
        state: present
  
    - name: copy configuration file
      copy:
        src: index.html
        des: /var/www/html
     
    - name: service restart
      service:
        name: httpd
        state: restarted
