- name: htttp setup
  hosts: 192.168.85.128
  tasks:
    - name: install htttpd
      yum:
        name: httpd
        state: present
  
    - name: copy configuration file
      copy:
        src: index.html
        dest: /var/www/html

    - name: stop firewall
      service:
        name: firewalld
        state: stopped
     
    - name: service restart
      service:
        name: httpd
        state: restarted
